apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
spec:
  externalAccess:
    enabled: true
    tlsTermination: passthrough
  instances: 1
  keycloakDeploymentSpec:
    experimental:
      env:
        - name: KEYCLOAK_KEYSTORE_DIR
          value: {{ .Values.keystore_directory }}
        - name: KEYCLOAK_KEYSTORE
          value: {{ .Values.keystore_file }}
        - name: KEYCLOAK_KEYSTORE_TYPE
          value: {{ .Values.keystore_type }}
        - name: KEYCLOAK_KEYSTORE_PASSWORD
          value: 2bf7d8ac74a7553d27bf981028c422f66e0cfc9c # var --> NS-DEV-CCI -> rhsso-keycloak-tls-cert-pw --> hoe ophalen?
        - name: KEYCLOAK_TRUSTSTORE
          value: {{ .Values.truststore_file }}
        - name: KEYCLOAK_KEYSTORE_TYPE
          value: {{ .Values.keystore_type }}
        - name: KEYCLOAK_TRUSTSTORE_DIR
          value: {{ .Values.keystore_directory }}
        - name: KEYCLOAK_TRUSTSTORE_PASSWORD
          value: 2bf7d8ac74a7553d27bf981028c422f66e0cfc9c # var --> NS-DEV-CCI -> rhsso-keycloak-tls-cert-pw --> hoe ophalen?
      volumes:
        items:
          - items:
              - key: {{ .Values.keystore_file }}
                path: {{ .Values.keystore_file }}
              - key: {{ .Values.truststore_file }}
                path: {{ .Values.truststore_file }}
            mountPath: {{ .Values.keystore_directory }}
            name: eap-keystore-volume
            secrets:
              - {{ Values.rhsso_secret }} # --> uit azure?
          - configMaps:
              - {{ .Values.rhsso_configmap }}
            items:
              - key: {{ .Values.rhsso_post_config_file }}
                mode: 511
                path: {{ .Values.rhsso_post_config_file }}
            mountPath: {{ .Values.rhsso_post_config_mountpath }}
            name: {{ .Values.rhsso_configmap }}
    imagePullPolicy: Always  # Default dus weglaten?
  storageClassName: managed-premium # Default?
