apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
  name: sandbox-keycloak # var
  namespace: rhsso  # var
spec:
  externalAccess:
    enabled: true
    tlsTermination: passthrough
  instances: 1
  keycloakDeploymentSpec:
    experimental:
      env:
        - name: KEYCLOAK_KEYSTORE_DIR
          value: /opt/keycloak/secret  # var
        - name: KEYCLOAK_KEYSTORE
          value: keystore.ks # var
        - name: KEYCLOAK_KEYSTORE_TYPE
          value: JKS # var
        - name: KEYCLOAK_KEYSTORE_PASSWORD
          value: 2bf7d8ac74a7553d27bf981028c422f66e0cfc9c # var --> NS-DEV-CCI -> rhsso-keycloak-tls-cert-pw --> hoe ophalen?
        - name: KEYCLOAK_TRUSTSTORE
          value: truststore.ts # var
        - name: KEYCLOAK_KEYSTORE_TYPE
          value: JKS # var
        - name: KEYCLOAK_TRUSTSTORE_DIR
          value: /opt/keycloak/secret # var
        - name: KEYCLOAK_TRUSTSTORE_PASSWORD
          value: 2bf7d8ac74a7553d27bf981028c422f66e0cfc9c # var --> NS-DEV-CCI -> rhsso-keycloak-tls-cert-pw --> hoe ophalen?
      volumes:
        items:
          - items:
              - key: keystore.ks  # var
                path: keystore.ks # var
              - key: truststore.ts # var
                path: truststore.ts # var
            mountPath: /opt/keycloak/secret # var
            name: eap-keystore-volume
            secrets:
              - rhsso-keycloak-tls-cert # var ?
          - configMaps:
              - keycloak-postconfigure
            items:
              - key: postconfigure.sh
                mode: 511
                path: postconfigure.sh
            mountPath: /opt/eap/extensions
            name: keycloak-postconfigure
    imagePullPolicy: Always
  storageClassName: managed-premium
status:
  credentialSecret: credential-sandbox-keycloak
  externalURL: https://keycloak-rhsso.apps.v2c6zabo.westeurope.aroapp.io
  internalURL: https://keycloak.rhsso.svc:8443
  message: 'Route.route.openshift.io "keycloak-metrics-rewrite" is invalid: spec.path:
    Invalid value: "/auth/realms/master/metrics": passthrough termination does not
    support paths'
  phase: failing
  ready: false
  secondaryResources:
    ConfigMap:
      - keycloak-probes
    Deployment:
      - keycloak-postgresql
    GrafanaDashboard:
      - keycloak
    PersistentVolumeClaim:
      - keycloak-postgresql-claim
    PrometheusRule:
      - keycloak
    Route:
      - keycloak
      - keycloak-metrics-rewrite
    Secret:
      - credential-sandbox-keycloak
      - keycloak-db-secret
    Service:
      - keycloak-postgresql
      - keycloak
      - keycloak-discovery
      - keycloak-monitoring
    ServiceMonitor:
      - keycloak-service-monitor
    StatefulSet:
      - keycloak
  version: main
